# backend/evaluator.py
import logging
from typing import List, Dict, Any, Tuple, Optional, Union # Added Union

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser, StrOutputParser
from pydantic import BaseModel, Field, ValidationError # Pydantic v2
from langchain_core.tools import BaseTool 
from langchain_core.runnables import RunnableConfig
from langchain_core.callbacks.base import BaseCallbackHandler, BaseCallbackManager # Added BaseCallbackManager

from backend.config import settings
from backend.llm_setup import get_llm
# PlanStep might not be strictly needed if current_plan_step is passed as dict
from backend.planner import PlanStep 
from backend.callbacks import LOG_SOURCE_EVALUATOR_STEP, LOG_SOURCE_EVALUATOR_OVERALL

logger = logging.getLogger(__name__)

class StepCorrectionOutcome(BaseModel): 
    step_achieved_goal: bool = Field(description="Boolean indicating if the step's primary goal was achieved based on the executor's output.")
    assessment_of_step: str = Field(description="Detailed assessment of the step's outcome, explaining why it succeeded or failed. If failed, explain the discrepancy between expected and actual outcome.")
    is_recoverable_via_retry: Optional[bool] = Field(default=None, description="If step_achieved_goal is false, boolean indicating if the step might be recoverable with a retry using a modified approach. Null if goal achieved.")
    suggested_new_tool_for_retry: Optional[str] = Field(default=None, description="If recoverable, the suggested tool name for the retry attempt (can be 'None'). Null if not recoverable or goal achieved.")
    suggested_new_input_instructions_for_retry: Optional[str] = Field(
        default=None,
        description="If recoverable, new or revised input instructions for the Controller to formulate the tool_input for the retry. Null if not recoverable or goal achieved. **Crucially, if the failure was because the Executor described its action or output instead of providing the direct content, these instructions MUST explicitly guide the Controller to instruct the Executor to output ONLY the raw content itself in its 'Final Answer'.**"
    )
    confidence_in_correction: Optional[float] = Field(default=None, description="If recoverable, confidence (0.0-1.0) in the suggested correction. Null if not recoverable or goal achieved.")

STEP_EVALUATOR_SYSTEM_PROMPT_TEMPLATE = """You are an expert Step Evaluator for a research agent. Your task is to meticulously assess if a single executed plan step achieved its intended goal, based on its output and the original expectations.
**Context for Evaluation:**
- Original User Query: {original_user_query}
- Current Plan Step Being Evaluated:
    - Description: {current_step_description}
    - Expected Outcome (from Planner): {current_step_expected_outcome}
- Controller's Decision for this attempt:
    - Tool Used by Executor: {controller_tool_used}
    - Formulated Input for Executor/Tool: {controller_tool_input}
- Actual Output from Executor/Tool for this attempt (`step_executor_output`):
  ---
  {step_executor_output}
  ---

**Your Evaluation Task:**
1.  Determine `step_achieved_goal` (True/False): Did the `step_executor_output` successfully fulfill the `current_step_expected_outcome`? Be strict but fair.

    * **Content Expectation Check (CRITICAL):**
        * If the `current_step_expected_outcome` implies the generation or availability of specific *content* (e.g., "A comprehensive research report...", "The text of a poem...", "Python code to perform X..."), then `step_achieved_goal` is True **ONLY IF the `step_executor_output` IS that actual content (or a substantial, directly usable part of it).**
        * A message *about* the content (e.g., "The report is generated and available," "The poem has been written," "Code is ready") is **NOT sufficient** for `step_achieved_goal` to be True if the `expected_outcome` was the content itself. The `step_executor_output` must *be* the report, poem, code, etc.
        * If `step_executor_output` is merely a descriptive message confirming an action, but the `expected_outcome` clearly implies the *resultant content* should be present, then `step_achieved_goal` MUST be False.
    * **Format Handling:**
        * If the `expected_outcome` is described as textual content that might be generated by an LLM (e.g., "Python script content", "JSON string", "Markdown report"), the `step_executor_output` might be enclosed in Markdown code fences (e.g., ```python ... ``` or ```json ... ``` or ```markdown ... ```).
        * In such cases, you should **evaluate the content *within* the fences**. The presence of the fences themselves does not mean the goal wasn't achieved if the inner content matches the expectation.
2.  Provide a detailed `assessment_of_step`: Explain your reasoning for True/False. If False, clearly state what went wrong, what was missing, or how the `step_executor_output` failed to meet the true intent of the `current_step_expected_outcome` (especially regarding content vs. description of content).
3.  If `step_achieved_goal` is False:
    a. Determine `is_recoverable_via_retry` (True/False): Could a different tool, different tool input, or a slightly modified approach likely succeed on a retry? Consider if the error was transient, a misunderstanding, or a fundamental flaw. Max retries are limited.
    b. If `is_recoverable_via_retry` is True:
        i. `suggested_new_tool_for_retry`: From the available tools ({available_tools_summary}), suggest the best tool for a retry (can be 'None' if the LLM should try again directly).
        ii. `suggested_new_input_instructions_for_retry`: Provide clear, revised instructions for the Controller to formulate the new tool input for the retry. **Crucially, if the failure was due to the Executor describing its action or output instead of providing the direct content, these instructions MUST explicitly guide the Controller to instruct the Executor to: 'Your Final Answer for this step must be ONLY the [specific expected content, e.g., the synthesized report, the generated code], without any introductory phrases, self-reflection, or meta-commentary regarding your process.'**
        iii. `confidence_in_correction`: Your confidence (0.0-1.0) that this suggested retry approach will succeed.
Output ONLY a JSON object adhering to this schema:
{format_instructions}

Do not include any preamble or explanation outside the JSON object.
"""

class EvaluationResult(BaseModel): 
    overall_success: bool = Field(description="Boolean indicating if the overall user query was successfully addressed by the executed plan.")
    confidence_score: float = Field(description="A score from 0.0 to 1.0 indicating confidence in the success/failure assessment.")
    assessment: str = Field(description="A concise, user-facing explanation of why the plan succeeded or failed overall, OR a brief confirmation if successful and final_answer_content is provided.")
    final_answer_content: Optional[str] = Field(
        default=None,
        description="If overall_success is True and the plan generated a direct user-facing answer (typically from the last step), this field MUST contain that exact, complete answer. Otherwise, it should be null or omitted."
    )
    suggestions_for_replan: Optional[List[str]] = Field(default=None, description="If the plan failed, a list of high-level suggestions for how a new plan might better achieve the goal. Null if successful.")

OVERALL_EVALUATOR_SYSTEM_PROMPT_TEMPLATE = """You are an expert Overall Plan Evaluator for a research agent.
Your task is to assess if the executed multi-step plan successfully achieved the user's original query, based on a summary of the plan's execution and the final answer produced by the last step of the plan.

**Context for Overall Evaluation:**
- Original User Query: {original_user_query}
- Summary of Executed Plan Steps & Outcomes:
  ---
  {executed_plan_summary}
  ---
- Output from the last successful plan step (this is the primary candidate for the user's final answer):
  ---
  {final_agent_answer}
  ---

**Your Evaluation Task:**
1.  `overall_success` (True/False): Did the agent, through the executed plan, fully and accurately address all aspects of the `original_user_query`?
    * Consider if the `final_agent_answer` (output from the last step) appropriately fulfills the user's request.
2.  `confidence_score` (0.0-1.0): Your confidence in this assessment.
3.  `final_answer_content`:
    * If `overall_success` is True AND the `final_agent_answer` (output from the last step) is the direct, complete, and appropriate answer for the user (e.g., it's the synthesized report, the generated text, not just a confirmation like "file written"), then this field MUST contain the **exact, verbatim content of `final_agent_answer`**.
    * If `overall_success` is True but the `final_agent_answer` is just a confirmation message (e.g., "File 'report.txt' written successfully to workspace.") and not the substantive content the user ultimately wanted to see, this `final_answer_content` field should be null or omitted.
    * If `overall_success` is False, this field MUST be null or omitted.
4.  `assessment`:
    * If `overall_success` is True and `final_answer_content` is populated (meaning the last step's output is the final answer), this `assessment` field should be a *very brief* confirmation message, like "The plan completed successfully and the information has been synthesized." or "All steps executed as planned. Here is the result:"
    * If `overall_success` is True but `final_answer_content` is null (e.g., the plan involved actions like writing files but no direct textual answer was expected from the last step for display), this `assessment` field should briefly summarize what was achieved (e.g., "The research was completed and files were generated as requested.").
    * If `overall_success` is False, this `assessment` field should be a concise, user-facing explanation of *why* the plan failed overall.
5.  `suggestions_for_replan` (Optional List[str]): If `overall_success` is False, provide a few high-level, actionable suggestions for how a *new* plan (if the user chooses to re-engage) might better achieve the original goal. These are not detailed steps, but strategic advice.

Output ONLY a JSON object adhering to this schema:
{format_instructions}

Do not include any preamble or explanation outside of the JSON object.
"""

async def evaluate_step_outcome_and_suggest_correction(
    original_user_query: str,
    current_plan_step: Dict[str, Any], # Expecting a dict representation of PlanStep
    controller_tool_used: Optional[str],
    controller_tool_input: Optional[str],
    step_executor_output: str,
    available_tools: List[BaseTool], 
    evaluator_llm_id_override: Optional[str] = None, # For Evaluator's own LLM
    callback_handler: Union[List[BaseCallbackHandler], BaseCallbackManager, None] = None
) -> Dict[str, Any]: # Returns a dict to update ResearchAgentState's step_evaluation_* fields
    """
    Evaluates a single plan step's outcome and suggests corrections if needed.
    """
    step_desc_for_log = current_plan_step.get('description', 'N/A')[:50]
    logger.info(f"Evaluator (Step): Evaluating step '{step_desc_for_log}...'")

    llm_provider_to_use = settings.evaluator_provider
    llm_model_to_use = settings.evaluator_model_name

    if evaluator_llm_id_override:
        try:
            provider_override, model_override = evaluator_llm_id_override.split("::", 1)
            if provider_override in ["gemini", "ollama"] and model_override:
                llm_provider_to_use, llm_model_to_use = provider_override, model_override
                logger.info(f"Evaluator (Step): Using session override LLM for Step Evaluator: {evaluator_llm_id_override}")
            else:
                logger.warning(f"Evaluator (Step): Invalid structure or provider in LLM override '{evaluator_llm_id_override}'. Using system default.")
        except ValueError:
            logger.warning(f"Evaluator (Step): Invalid LLM override format '{evaluator_llm_id_override}'. Using system default.")
    
    try:
        evaluator_llm: BaseChatModel = get_llm(
            settings,
            provider=llm_provider_to_use,
            model_name=llm_model_to_use,
            requested_for_role=LOG_SOURCE_EVALUATOR_STEP,
            callbacks=callback_handler
        )
        logger.info(f"Evaluator (Step): Using LLM {llm_provider_to_use}::{llm_model_to_use}")
    except Exception as e:
        logger.error(f"Evaluator (Step): Failed to initialize LLM: {e}", exc_info=True)
        return {
            "step_evaluation_achieved_goal": False,
            "step_evaluation_assessment": f"LLM initialization failed for Step Evaluator: {e}",
            "step_evaluation_is_recoverable": False,
            "step_evaluation_error": f"LLM initialization failed: {e}"
        }

    parser = JsonOutputParser(pydantic_object=StepCorrectionOutcome)
    format_instructions = parser.get_format_instructions()
    tools_summary_for_eval = "\n".join([f"- {tool.name}: {tool.description.split('.')[0]}" for tool in available_tools])

    prompt = ChatPromptTemplate.from_messages([
        ("system", STEP_EVALUATOR_SYSTEM_PROMPT_TEMPLATE),
        ("human", "Evaluate the step execution based on the provided context and output your assessment in the specified JSON format.")
    ])
    
    chain = prompt | evaluator_llm | parser
    
    invoke_payload = {
        "original_user_query": original_user_query,
        "current_step_description": current_plan_step.get('description', 'N/A'),
        "current_step_expected_outcome": current_plan_step.get('expected_outcome', 'N/A'),
        "controller_tool_used": controller_tool_used or "None",
        "controller_tool_input": controller_tool_input or "None",
        "step_executor_output": step_executor_output,
        "available_tools_summary": tools_summary_for_eval,
        "format_instructions": format_instructions
    }
    run_config = RunnableConfig(
        callbacks=callback_handler if isinstance(callback_handler, BaseCallbackManager) else ([callback_handler] if callback_handler else None),
        metadata={"component_name": LOG_SOURCE_EVALUATOR_STEP}
    )
    error_message_for_state = None

    try:
        eval_outcome_model: StepCorrectionOutcome = await chain.ainvoke(invoke_payload, config=run_config)
        
        if isinstance(eval_outcome_model, dict): # Handle if parser returns dict
            logger.debug("Step Evaluator: LLM output parser returned a dict, validating with Pydantic model StepCorrectionOutcome.")
            try:
                eval_outcome_model = StepCorrectionOutcome(**eval_outcome_model)
            except ValidationError as ve_eval:
                logger.error(f"Step Evaluator: Pydantic validation failed for StepCorrectionOutcome from LLM dict: {ve_eval}. Raw dict: {eval_outcome_model}", exc_info=True)
                raise

        logger.info(f"Evaluator (Step): Achieved Goal: {eval_outcome_model.step_achieved_goal}, Recoverable: {eval_outcome_model.is_recoverable_via_retry}, Assessment: {eval_outcome_model.assessment_of_step}")
        # Map StepCorrectionOutcome fields to state fields
        return {
            "step_evaluation_achieved_goal": eval_outcome_model.step_achieved_goal,
            "step_evaluation_assessment": eval_outcome_model.assessment_of_step,
            "step_evaluation_is_recoverable": eval_outcome_model.is_recoverable_via_retry,
            "step_evaluation_suggested_tool": eval_outcome_model.suggested_new_tool_for_retry,
            "step_evaluation_suggested_input_instructions": eval_outcome_model.suggested_new_input_instructions_for_retry,
            "step_evaluation_confidence_in_correction": eval_outcome_model.confidence_in_correction,
            "step_evaluation_error": None
        }
    except ValidationError as ve:
         logger.error(f"Step Evaluator: Pydantic validation error for StepCorrectionOutcome: {ve}", exc_info=True)
         error_message_for_state = f"Step Evaluator output validation failed: {ve}"
    except Exception as e:
        logger.error(f"Evaluator (Step): Error during step evaluation for step '{step_desc_for_log}': {e}", exc_info=True)
        error_message_for_state = f"Unexpected error in Step Evaluator: {type(e).__name__} - {str(e)}"

    # Attempt to get raw output on error
    try:
        raw_output_chain = prompt | evaluator_llm | StrOutputParser()
        raw_output = await raw_output_chain.ainvoke(invoke_payload, config=run_config) # Use same config
        logger.error(f"Step Evaluator: Raw LLM output on error: {raw_output}")
        if error_message_for_state:
             error_message_for_state += f". Raw LLM output: {raw_output[:200]}..."
        else:
             error_message_for_state = f"Step Evaluator failed. Raw LLM output: {raw_output[:200]}..."
    except Exception as raw_e:
        logger.error(f"Step Evaluator: Failed to get raw LLM output on error: {raw_e}")
        if error_message_for_state:
            error_message_for_state += ". Failed to retrieve raw LLM output."
        else:
            error_message_for_state = "Step Evaluator failed and could not retrieve raw LLM output."
            
    return {
        "step_evaluation_achieved_goal": False, # Default to false on error
        "step_evaluation_assessment": error_message_for_state or "Step evaluation failed due to an internal error.",
        "step_evaluation_is_recoverable": False, # Default to not recoverable on error
        "step_evaluation_error": error_message_for_state or "Step evaluation failed."
    }


async def evaluate_plan_outcome( # This function remains for future use with OverallEvaluatorNode
    original_user_query: str,
    executed_plan_summary: str,
    final_agent_answer: str,
    evaluator_llm_id_override: Optional[str] = None,
    callback_handler: Union[List[BaseCallbackHandler], BaseCallbackManager, None] = None
) -> Optional[EvaluationResult]: # Returns the Pydantic model or None on error
    # ... (Implementation of evaluate_plan_outcome - can be adapted similarly later) ...
    logger.info(f"Evaluator (Overall Plan): Evaluating outcome for query: {original_user_query[:100]}...")
    # For now, this function is not the primary focus of refactoring for the step loop.
    # It will be adapted when we build the OverallEvaluatorNode.
    return None


# if __name__ == '__main__':
    # Standalone testing for evaluate_step_outcome_and_suggest_correction would be complex
    # due to dependencies on PlanStep structure, available_tools, and LLM calls.
    # It's better tested via the langgraph_agent.py test runner.
