# backend/evaluator.py
import logging
from typing import List, Dict, Any, Tuple, Optional, Union 

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser, StrOutputParser
from pydantic import BaseModel, Field, ValidationError 
from langchain_core.tools import BaseTool 
from langchain_core.runnables import RunnableConfig
from langchain_core.callbacks.base import BaseCallbackHandler, BaseCallbackManager 

from backend.config import settings
from backend.llm_setup import get_llm
from backend.planner import PlanStep 
from backend.callbacks import LOG_SOURCE_EVALUATOR_STEP, LOG_SOURCE_EVALUATOR_OVERALL

logger = logging.getLogger(__name__)

class StepCorrectionOutcome(BaseModel): 
    step_achieved_goal: bool = Field(description="Boolean indicating if the step's primary goal was achieved based on the executor's output.")
    assessment_of_step: str = Field(description="Detailed assessment of the step's outcome, explaining why it succeeded or failed. If failed, explain the discrepancy between expected and actual outcome.")
    is_recoverable_via_retry: Optional[bool] = Field(default=None, description="If step_achieved_goal is false, boolean indicating if the step might be recoverable with a retry using a modified approach. Null if goal achieved.")
    suggested_new_tool_for_retry: Optional[str] = Field(default=None, description="If recoverable, the suggested tool name for the retry attempt (can be 'None'). Null if not recoverable or goal achieved.")
    suggested_new_input_instructions_for_retry: Optional[str] = Field(
        default=None,
        description="If recoverable, new or revised input instructions for the Controller to formulate the tool_input for the retry. Null if not recoverable or goal achieved. **Crucially, if the failure was because the Executor described its action or output instead of providing the direct content, these instructions MUST explicitly guide the Controller to instruct the Executor to output ONLY the raw content itself in its 'Final Answer'.**"
    )
    confidence_in_correction: Optional[float] = Field(default=None, description="If recoverable, confidence (0.0-1.0) in the suggested correction. Null if not recoverable or goal achieved.")

STEP_EVALUATOR_SYSTEM_PROMPT_TEMPLATE = """You are an expert Step Evaluator for a research agent. Your task is to meticulously assess if a single executed plan step achieved its intended goal, based on its output and the original expectations.
**Context for Evaluation:**
- Original User Query: {original_user_query}
- Current Plan Step Being Evaluated:
    - Description: {current_step_description}
    - Expected Outcome (from Planner): {current_step_expected_outcome}
- Controller's Decision for this attempt:
    - Tool Used by Executor: {controller_tool_used}
    - Formulated Input for Executor/Tool: {controller_tool_input}
- Actual Output from Executor/Tool for this attempt (`step_executor_output`):
  ---
  {step_executor_output}
  ---

**Your Evaluation Task:**
1.  Determine `step_achieved_goal` (True/False): Did the `step_executor_output` successfully fulfill the `current_step_expected_outcome`? Be strict but fair.

    * **Content Expectation Check (CRITICAL):**
        * If the `current_step_expected_outcome` implies the generation or availability of specific *content* (e.g., "A comprehensive research report...", "The text of a poem...", "Python code to perform X..."), then `step_achieved_goal` is True **ONLY IF the `step_executor_output` IS that actual content (or a substantial, directly usable part of it).**
        * A message *about* the content (e.g., "The report is generated and available," "The poem has been written," "Code is ready") is **NOT sufficient** for `step_achieved_goal` to be True if the `expected_outcome` was the content itself. The `step_executor_output` must *be* the report, poem, code, etc.
        * If `step_executor_output` is merely a descriptive message confirming an action, but the `expected_outcome` clearly implies the *resultant content* should be present, then `step_achieved_goal` MUST be False.
    * **Format Handling:**
        * If the `expected_outcome` is described as textual content that might be generated by an LLM (e.g., "Python script content", "JSON string", "Markdown report"), the `step_executor_output` might be enclosed in Markdown code fences (e.g., ```python ... ``` or ```json ... ``` or ```markdown ... ```).
        * In such cases, you should **evaluate the content *within* the fences**. The presence of the fences themselves does not mean the goal wasn't achieved if the inner content matches the expectation.
2.  Provide a detailed `assessment_of_step`: Explain your reasoning for True/False. If False, clearly state what went wrong, what was missing, or how the `step_executor_output` failed to meet the true intent of the `current_step_expected_outcome` (especially regarding content vs. description of content).
3.  If `step_achieved_goal` is False:
    a. Determine `is_recoverable_via_retry` (True/False): Could a different tool, different tool input, or a slightly modified approach likely succeed on a retry? Consider if the error was transient, a misunderstanding, or a fundamental flaw. Max retries are limited.
    b. If `is_recoverable_via_retry` is True:
        i. `suggested_new_tool_for_retry`: From the available tools ({available_tools_summary}), suggest the best tool for a retry (can be 'None' if the LLM should try again directly).
        ii. `suggested_new_input_instructions_for_retry`: Provide clear, revised instructions for the Controller to formulate the new tool input for the retry. **Crucially, if the failure was due to the Executor describing its action or output instead of providing the direct content, these instructions MUST explicitly guide the Controller to instruct the Executor to: 'Your Final Answer for this step must be ONLY the [specific expected content, e.g., the synthesized report, the generated code], without any introductory phrases, self-reflection, or meta-commentary regarding your process.'**
        iii. `confidence_in_correction`: Your confidence (0.0-1.0) that this suggested retry approach will succeed.
Output ONLY a JSON object adhering to this schema:
{format_instructions}

Do not include any preamble or explanation outside the JSON object.
"""

class EvaluationResult(BaseModel): 
    overall_success: bool = Field(description="Boolean indicating if the overall user query was successfully addressed by the executed plan.")
    confidence_score: float = Field(description="A score from 0.0 to 1.0 indicating confidence in the success/failure assessment.")
    assessment: str = Field(description="A concise, user-facing explanation of why the plan succeeded or failed overall, OR a brief confirmation if successful and final_answer_content is provided.")
    final_answer_content: Optional[str] = Field(
        default=None,
        description="If overall_success is True and the plan generated a direct user-facing answer (typically from the last step), this field MUST contain that exact, complete answer. Otherwise, it should be null or omitted."
    )
    suggestions_for_replan: Optional[List[str]] = Field(default=None, description="If the plan failed, a list of high-level suggestions for how a new plan might better achieve the goal. Null if successful.")

OVERALL_EVALUATOR_SYSTEM_PROMPT_TEMPLATE = """You are an expert Overall Plan Evaluator for a research agent.
Your task is to assess if the executed multi-step plan successfully achieved the user's original query, based on a summary of the plan's execution and the final answer produced by the last step of the plan.

**Context for Overall Evaluation:**
- Original User Query: {original_user_query}
- Summary of Executed Plan Steps & Outcomes (e.g., a log of messages, or a summary of step successes/failures):
  ---
  {executed_plan_summary_str}
  ---
- Output from the last successful plan step (this is the primary candidate for the user's final answer, if applicable):
  ---
  {final_agent_answer_from_last_step}
  ---

**Your Evaluation Task:**
1.  `overall_success` (True/False): Did the agent, through the executed plan, fully and accurately address all aspects of the `original_user_query`?
    * Consider if the `final_agent_answer_from_last_step` (output from the last step) appropriately fulfills the user's request.
2.  `confidence_score` (0.0-1.0): Your confidence in this assessment.
3.  `final_answer_content`:
    * If `overall_success` is True AND the `final_agent_answer_from_last_step` is the direct, complete, and appropriate answer for the user (e.g., it's the synthesized report, the generated text, not just a confirmation like "file written"), then this field MUST contain the **exact, verbatim content of `final_agent_answer_from_last_step`**.
    * If `overall_success` is True but the `final_agent_answer_from_last_step` is just a confirmation message (e.g., "File 'report.txt' written successfully to workspace.") and not the substantive content the user ultimately wanted to see, this `final_answer_content` field should be null or omitted.
    * If `overall_success` is False, this field MUST be null or omitted.
4.  `assessment`:
    * If `overall_success` is True and `final_answer_content` is populated (meaning the last step's output is the final answer), this `assessment` field should be a *very brief* confirmation message, like "The plan completed successfully and the information has been synthesized." or "All steps executed as planned. Here is the result:"
    * If `overall_success` is True but `final_answer_content` is null (e.g., the plan involved actions like writing files but no direct textual answer was expected from the last step for display), this `assessment` field should briefly summarize what was achieved (e.g., "The research was completed and files were generated as requested.").
    * If `overall_success` is False, this `assessment` field should be a concise, user-facing explanation of *why* the plan failed overall.
5.  `suggestions_for_replan` (Optional List[str]): If `overall_success` is False, provide a few high-level, actionable suggestions for how a *new* plan (if the user chooses to re-engage) might better achieve the original goal. These are not detailed steps, but strategic advice.

Output ONLY a JSON object adhering to this schema:
{format_instructions}

Do not include any preamble or explanation outside of the JSON object.
"""

async def evaluate_step_outcome_and_suggest_correction(
    original_user_query: str,
    current_plan_step: Dict[str, Any], 
    controller_tool_used: Optional[str],
    controller_tool_input: Optional[str],
    step_executor_output: str,
    available_tools: List[BaseTool], 
    evaluator_llm_id_override: Optional[str] = None, 
    callback_handler: Union[List[BaseCallbackHandler], BaseCallbackManager, None] = None
) -> Dict[str, Any]: 
    step_desc_for_log = current_plan_step.get('description', 'N/A')[:50]
    logger.info(f"Evaluator (Step): Evaluating step '{step_desc_for_log}...'")
    llm_provider_to_use = settings.evaluator_provider
    llm_model_to_use = settings.evaluator_model_name
    if evaluator_llm_id_override:
        try:
            provider_override, model_override = evaluator_llm_id_override.split("::", 1)
            if provider_override in ["gemini", "ollama"] and model_override:
                llm_provider_to_use, llm_model_to_use = provider_override, model_override
                logger.info(f"Evaluator (Step): Using session override LLM for Step Evaluator: {evaluator_llm_id_override}")
        except ValueError: logger.warning(f"Evaluator (Step): Invalid LLM override format '{evaluator_llm_id_override}'. Using system default.")
    try:
        evaluator_llm: BaseChatModel = get_llm(
            settings, provider=llm_provider_to_use, model_name=llm_model_to_use,
            requested_for_role=LOG_SOURCE_EVALUATOR_STEP, callbacks=callback_handler)
        logger.info(f"Evaluator (Step): Using LLM {llm_provider_to_use}::{llm_model_to_use}")
    except Exception as e:
        logger.error(f"Evaluator (Step): Failed to initialize LLM: {e}", exc_info=True)
        return {"step_evaluation_achieved_goal": False, "step_evaluation_assessment": f"LLM init failed: {e}", "step_evaluation_is_recoverable": False, "step_evaluation_error": f"LLM init failed: {e}"}
    parser = JsonOutputParser(pydantic_object=StepCorrectionOutcome)
    format_instructions = parser.get_format_instructions()
    tools_summary_for_eval = "\n".join([f"- {tool.name}: {tool.description.split('.')[0]}" for tool in available_tools])
    prompt = ChatPromptTemplate.from_messages([("system", STEP_EVALUATOR_SYSTEM_PROMPT_TEMPLATE), ("human", "Evaluate step execution.")])
    chain = prompt | evaluator_llm | parser
    invoke_payload = {
        "original_user_query": original_user_query,
        "current_step_description": current_plan_step.get('description', 'N/A'),
        "current_step_expected_outcome": current_plan_step.get('expected_outcome', 'N/A'),
        "controller_tool_used": controller_tool_used or "None",
        "controller_tool_input": controller_tool_input or "None",
        "step_executor_output": step_executor_output,
        "available_tools_summary": tools_summary_for_eval,
        "format_instructions": format_instructions
    }
    run_config = RunnableConfig(
        callbacks=callback_handler if isinstance(callback_handler, BaseCallbackManager) else ([callback_handler] if callback_handler else None),
        metadata={"component_name": LOG_SOURCE_EVALUATOR_STEP})
    error_message_for_state = None
    try:
        eval_outcome_model: StepCorrectionOutcome = await chain.ainvoke(invoke_payload, config=run_config)
        if isinstance(eval_outcome_model, dict):
            eval_outcome_model = StepCorrectionOutcome(**eval_outcome_model)
        logger.info(f"Evaluator (Step): Achieved: {eval_outcome_model.step_achieved_goal}, Recoverable: {eval_outcome_model.is_recoverable_via_retry}, Assessment: {eval_outcome_model.assessment_of_step}")
        return {
            "step_evaluation_achieved_goal": eval_outcome_model.step_achieved_goal,
            "step_evaluation_assessment": eval_outcome_model.assessment_of_step,
            "step_evaluation_is_recoverable": eval_outcome_model.is_recoverable_via_retry,
            "step_evaluation_suggested_tool": eval_outcome_model.suggested_new_tool_for_retry,
            "step_evaluation_suggested_input_instructions": eval_outcome_model.suggested_new_input_instructions_for_retry,
            "step_evaluation_confidence_in_correction": eval_outcome_model.confidence_in_correction,
            "step_evaluation_error": None
        }
    except ValidationError as ve: error_message_for_state = f"Output validation failed: {ve}"
    except Exception as e: error_message_for_state = f"Unexpected error: {type(e).__name__} - {str(e)}"
    logger.error(f"Evaluator (Step) Error: {error_message_for_state}", exc_info=True)
    try: # Attempt to get raw output on error
        raw_output = await (prompt | evaluator_llm | StrOutputParser()).ainvoke(invoke_payload, config=run_config)
        logger.error(f"Step Evaluator Raw LLM output on error: {raw_output}")
        error_message_for_state += f". Raw LLM: {raw_output[:200]}..."
    except Exception as raw_e: error_message_for_state += f". Failed to get raw LLM output: {raw_e}"
    return {"step_evaluation_achieved_goal": False, "step_evaluation_assessment": error_message_for_state, "step_evaluation_is_recoverable": False, "step_evaluation_error": error_message_for_state}

async def evaluate_plan_outcome(
    original_user_query: str,
    executed_plan_summary_str: str, # String summarizing step outcomes
    final_agent_answer_from_last_step: Optional[str], # Output of the last successful step
    evaluator_llm_id_override: Optional[str] = None,
    callback_handler: Union[List[BaseCallbackHandler], BaseCallbackManager, None] = None
) -> Dict[str, Any]: # Returns a dict to update ResearchAgentState's overall_evaluation_* fields
    """
    Evaluates the overall outcome of the executed plan.
    """
    logger.info(f"Evaluator (Overall Plan): Evaluating outcome for query: '{original_user_query[:100]}...'")
    logger.debug(f"Evaluator (Overall Plan): Executed plan summary string: '{executed_plan_summary_str[:300]}...'")
    logger.debug(f"Evaluator (Overall Plan): Final agent answer from last step: '{str(final_agent_answer_from_last_step)[:300]}...'")

    llm_provider_to_use = settings.evaluator_provider # Could use a different setting for overall if needed
    llm_model_to_use = settings.evaluator_model_name

    if evaluator_llm_id_override: # Allow override for overall evaluator too
        try:
            provider_override, model_override = evaluator_llm_id_override.split("::", 1)
            if provider_override in ["gemini", "ollama"] and model_override:
                llm_provider_to_use, llm_model_to_use = provider_override, model_override
                logger.info(f"Evaluator (Overall): Using session override LLM: {evaluator_llm_id_override}")
        except ValueError:
            logger.warning(f"Evaluator (Overall): Invalid LLM override format '{evaluator_llm_id_override}'. Using system default.")
    
    try:
        overall_eval_llm: BaseChatModel = get_llm(
            settings,
            provider=llm_provider_to_use,
            model_name=llm_model_to_use,
            requested_for_role=LOG_SOURCE_EVALUATOR_OVERALL,
            callbacks=callback_handler
        )
        logger.info(f"Evaluator (Overall): Using LLM {llm_provider_to_use}::{llm_model_to_use}")
    except Exception as e:
        logger.error(f"Evaluator (Overall): Failed to initialize LLM: {e}", exc_info=True)
        return {
            "overall_evaluation_success": False,
            "overall_evaluation_assessment": f"LLM initialization failed for Overall Evaluator: {e}",
            "overall_evaluation_error": f"LLM initialization failed: {e}"
        }

    parser = JsonOutputParser(pydantic_object=EvaluationResult)
    format_instructions = parser.get_format_instructions()

    prompt = ChatPromptTemplate.from_messages([
        ("system", OVERALL_EVALUATOR_SYSTEM_PROMPT_TEMPLATE),
        ("human", "Evaluate the overall plan execution based on the provided context and output your assessment in the specified JSON format.")
    ])
    
    chain = prompt | overall_eval_llm | parser
    
    invoke_payload = {
        "original_user_query": original_user_query,
        "executed_plan_summary_str": executed_plan_summary_str,
        "final_agent_answer_from_last_step": final_agent_answer_from_last_step or "No direct final answer content from last step.",
        "format_instructions": format_instructions
    }
    run_config = RunnableConfig(
        callbacks=callback_handler if isinstance(callback_handler, BaseCallbackManager) else ([callback_handler] if callback_handler else None),
        metadata={"component_name": LOG_SOURCE_EVALUATOR_OVERALL}
    )
    error_message_for_state = None

    try:
        eval_result_model: EvaluationResult = await chain.ainvoke(invoke_payload, config=run_config)
        
        if isinstance(eval_result_model, dict): # Handle if parser returns dict
            logger.debug("Overall Evaluator: LLM output parser returned a dict, validating with Pydantic model EvaluationResult.")
            try:
                eval_result_model = EvaluationResult(**eval_result_model)
            except ValidationError as ve_overall:
                logger.error(f"Overall Evaluator: Pydantic validation failed for EvaluationResult from LLM dict: {ve_overall}. Raw dict: {eval_result_model}", exc_info=True)
                raise

        logger.info(f"Evaluator (Overall): Success: {eval_result_model.overall_success}, Assessment: '{eval_result_model.assessment}'")
        # Map EvaluationResult fields to state fields
        return {
            "overall_evaluation_success": eval_result_model.overall_success,
            "overall_evaluation_assessment": eval_result_model.assessment,
            "overall_evaluation_final_answer_content": eval_result_model.final_answer_content,
            "overall_evaluation_suggestions_for_replan": eval_result_model.suggestions_for_replan,
            "overall_evaluation_error": None # Clear error if successful
        }
    except ValidationError as ve:
         logger.error(f"Overall Evaluator: Pydantic validation error for EvaluationResult: {ve}", exc_info=True)
         error_message_for_state = f"Overall Evaluator output validation failed: {ve}"
    except Exception as e:
        logger.error(f"Evaluator (Overall): Error during overall plan evaluation: {e}", exc_info=True)
        error_message_for_state = f"Unexpected error in Overall Evaluator: {type(e).__name__} - {str(e)}"

    # Attempt to get raw output on error
    try:
        raw_output_chain = prompt | overall_eval_llm | StrOutputParser()
        raw_output = await raw_output_chain.ainvoke(invoke_payload, config=run_config)
        logger.error(f"Overall Evaluator: Raw LLM output on error: {raw_output}")
        if error_message_for_state: error_message_for_state += f". Raw LLM: {raw_output[:200]}..."
        else: error_message_for_state = f"Overall Evaluator failed. Raw LLM: {raw_output[:200]}..."
    except Exception as raw_e:
        logger.error(f"Overall Evaluator: Failed to get raw LLM output on error: {raw_e}")
        if error_message_for_state: error_message_for_state += ". Failed to get raw LLM output."
        else: error_message_for_state = "Overall Evaluator failed and could not retrieve raw LLM output."
            
    return {
        "overall_evaluation_success": False, # Default to false on error
        "overall_evaluation_assessment": error_message_for_state or "Overall plan evaluation failed due to an internal error.",
        "overall_evaluation_error": error_message_for_state or "Overall plan evaluation failed."
    }
